//------------------------------------------------------------------------------
//Filename       inttest.h
//System         
//Author         Robert Slater
//Date           Mon 29 Nov 1999
//Description    
//------------------------------------------------------------------------------
#ifndef	INTTEST_Included
#define	INTTEST_Included

#define	DEFAULT_INTTEST 0



const ULong	IDS_ALTMETER = 0;
const ULong	IDS_CLOCK = 0;
const ULong	IDS_AIRSPEED = 0;
const ULong	IDS_ARTHORIZ = 0;
const ULong	IDS_CLIMB = 0;
const ULong	IDS_RADIOALT = 0;
const ULong	IDS_DIRECTION = 0;
const ULong	IDS_TURN = 0;
const ULong	IDS_MECHUC = 0;
const ULong	IDS_FUELCONTENT = 0;
const ULong	IDS_FUELPRESSURE = 0;
const ULong	IDS_OILCONTENT = 0;
const ULong	IDS_OILPRESSURE = 0;
const ULong	IDS_OILTEMP = 0;
const ULong	IDS_RADIATORTEMP = 0;
const ULong	IDS_BOOST = 0;
const ULong	IDS_VOLTMETER = 0;
const ULong	IDS_COMPASS = 0;
const ULong	IDS_PITCH = 0;
const ULong	IDS_FLAPINDICATOR = 0;
const ULong	IDS_GUNAMMO = 0;
const ULong	IDS_CANNONAMMO = 0;
const ULong	IDS_CONTROL = 0;
const ULong	IDS_RUDDER = 0;
const ULong	IDS_UNDERCARRIAGE = 0;
const ULong	IDS_ARMED = 0;
const ULong	IDS_UNDERFLAP = 0;
const ULong	IDS_ELEVATOR = 0;
const ULong	IDS_EMERGENCYUC = 0;
const ULong	IDS_THROTTLE = 0;
const ULong	IDS_PROPPITCH = 0;
const ULong	IDS_ENGINESPEED = 0;
const ULong	IDS_MIXTURE = 0;
const ULong	IDS_PRIMER = 0;
const ULong	IDS_FUELCOCK = 0;
const ULong	IDS_ENGINESTARTER = 0;
const ULong	IDS_BOOSTCUTOUT = 0;
const ULong	IDS_LANDING = 0;
const ULong	IDS_GUNCAM = 0;
const ULong	IDS_HOODCATCH = 0;
const ULong	IDS_HOODJETTISON = 0;
const ULong	IDS_FUELTANKSELECT = 0;
const ULong	IDS_MAGNETO = 0;
const ULong	IDS_FLAPSUP = 0;
const ULong	IDS_FLAPSDOWN = 0;




























#endif
