//------------------------------------------------------------------------------
//Filename       mapsfx.h
//System         
//Author         Robert Slater
//Date           Mon 8 May 2000
//Description    
//------------------------------------------------------------------------------
#ifndef	MAPSFX_Included
#define	MAPSFX_Included

#define	DEFAULT_MAPSFX 0


enum	MapSFX
{
	SFX_NULL=0,
	SFX_PhoneIn,
	SFX_PhoneOut,
	SFX_TeleType,
	SFX_AlertRaid,
	SFX_AlertScramble,
	SFX_OfficeAmbience
};



#endif
