//------------------------------------------------------------------------------
//Filename       mdistruc.h
//System         
//Author         Andy McMaster
//Date           Tue 23 Nov 1999
//Description    
//------------------------------------------------------------------------------
#ifndef	MDISTRUC_Included
#define	MDISTRUC_Included

#define	DEFAULT_MDISTRUC 0

#include	"Dmusici.h"

class Music;



#endif
